In [1]:
import numpy as np
import pandas as pd


In [2]:
data=pd.read_csv("Real estate.csv")

In [3]:
data.head()

No  X1 transaction date  X2 house age  \
0   1             2012.917          32.0   
1   2             2012.917          19.5   
2   3             2013.583          13.3   
3   4             2013.500          13.3   
4   5             2012.833           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
No                                        414 non-null int64
X1 transaction date                       414 non-null float64
X2 house age                              414 non-null float64
X3 distance to the nearest MRT station    414 non-null float64
X4 number of convenience stores           414 non-null int64
X5 latitude                               414 non-null float64
X6 longitude                              414 non-null float64
Y house price of unit area                414 non-null float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB


In [5]:
data.isnull().sum()

No                                        0
X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [6]:
x=data.iloc[:,1:7]
y=data.iloc[:,7]

In [7]:
x.head()

X1 transaction date  X2 house age  X3 distance to the nearest MRT station  \
0             2012.917          32.0                                84.87882   
1             2012.917          19.5                               306.59470   
2             2013.583          13.3                               561.98450   
3             2013.500          13.3                               561.98450   
4             2012.833           5.0                               390.56840   

   X4 number of convenience stores  X5 latitude  X6 longitude  
0                               10     24.98298     121.54024  
1                                9     24.98034     121.53951  
2                                5     24.98746     121.54391  
3                                5     24.98746     121.54391  
4                                5     24.97937     121.54245

In [8]:
y.head()

0    37.9
1    42.2
2    47.3
3    54.8
4    43.1
Name: Y house price of unit area, dtype: float64

In [9]:
x=data.iloc[:,1:7].values
y=data.iloc[:,7].values

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [13]:
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [15]:
ann=Sequential()

In [16]:
ann.add(Dense(6,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [17]:
ann.add(Dense(12,kernel_initializer="random_uniform",activation="relu"))

In [19]:
ann.add(Dense(1,kernel_initializer="random_uniform",activation="relu"))

In [20]:
ann.compile("adam","mse",metrics=["mse"])

In [21]:
ann.fit(x_train,y_train,batch_size=32,epochs=1000)

Epoch 1/1000
331/331 [==============================] - 0s 497us/sample - loss: 1629.1489 - mean_squared_error: 1629.1488
Epoch 2/1000
331/331 [==============================] - 0s 69us/sample - loss: 1627.8456 - mean_squared_error: 1627.8457
Epoch 3/1000
331/331 [==============================] - 0s 66us/sample - loss: 1626.1631 - mean_squared_error: 1626.1631
Epoch 4/1000
331/331 [==============================] - 0s 79us/sample - loss: 1623.7827 - mean_squared_error: 1623.7827
Epoch 5/1000
331/331 [==============================] - 0s 60us/sample - loss: 1620.4149 - mean_squared_error: 1620.4150
Epoch 6/1000
331/331 [==============================] - 0s 82us/sample - loss: 1615.4940 - mean_squared_error: 1615.4940
Epoch 7/1000
331/331 [==============================] - 0s 85us/sample - loss: 1608.5668 - mean_squared_error: 1608.5669
Epoch 8/1000
331/331 [==============================] - 0s 76us/sample - loss: 1598.9107 - mean_squared_error: 1598.9106
Epoch 9/1000
331/331 [=========

Epoch 69/1000
331/331 [==============================] - 0s 95us/sample - loss: 99.7123 - mean_squared_error: 99.7123
Epoch 70/1000
331/331 [==============================] - 0s 70us/sample - loss: 98.9427 - mean_squared_error: 98.9427
Epoch 71/1000
331/331 [==============================] - 0s 57us/sample - loss: 98.1718 - mean_squared_error: 98.1718
Epoch 72/1000
331/331 [==============================] - 0s 57us/sample - loss: 97.4570 - mean_squared_error: 97.4570
Epoch 73/1000
331/331 [==============================] - 0s 57us/sample - loss: 96.7894 - mean_squared_error: 96.7894
Epoch 74/1000
331/331 [==============================] - 0s 147us/sample - loss: 96.1528 - mean_squared_error: 96.1528
Epoch 75/1000
331/331 [==============================] - 0s 65us/sample - loss: 95.4846 - mean_squared_error: 95.4846
Epoch 76/1000
331/331 [==============================] - 0s 80us/sample - loss: 94.8363 - mean_squared_error: 94.8363
Epoch 77/1000
331/331 [==============================] 

331/331 [==============================] - 0s 54us/sample - loss: 72.5528 - mean_squared_error: 72.5528
Epoch 138/1000
331/331 [==============================] - 0s 85us/sample - loss: 72.4169 - mean_squared_error: 72.4169
Epoch 139/1000
331/331 [==============================] - 0s 54us/sample - loss: 72.2664 - mean_squared_error: 72.2664
Epoch 140/1000
331/331 [==============================] - 0s 66us/sample - loss: 72.1505 - mean_squared_error: 72.1505
Epoch 141/1000
331/331 [==============================] - 0s 54us/sample - loss: 72.0123 - mean_squared_error: 72.0123
Epoch 142/1000
331/331 [==============================] - 0s 54us/sample - loss: 71.7254 - mean_squared_error: 71.7253
Epoch 143/1000
331/331 [==============================] - 0s 69us/sample - loss: 71.6288 - mean_squared_error: 71.6288
Epoch 144/1000
331/331 [==============================] - 0s 51us/sample - loss: 71.4399 - mean_squared_error: 71.4399
Epoch 145/1000
331/331 [==============================] - 0s 60

Epoch 206/1000
331/331 [==============================] - 0s 73us/sample - loss: 67.7601 - mean_squared_error: 67.7601
Epoch 207/1000
331/331 [==============================] - 0s 79us/sample - loss: 67.7950 - mean_squared_error: 67.7950
Epoch 208/1000
331/331 [==============================] - 0s 60us/sample - loss: 67.7109 - mean_squared_error: 67.7109
Epoch 209/1000
331/331 [==============================] - 0s 51us/sample - loss: 67.7021 - mean_squared_error: 67.7021
Epoch 210/1000
331/331 [==============================] - 0s 70us/sample - loss: 67.6508 - mean_squared_error: 67.6508
Epoch 211/1000
331/331 [==============================] - 0s 140us/sample - loss: 67.7172 - mean_squared_error: 67.7172
Epoch 212/1000
331/331 [==============================] - 0s 57us/sample - loss: 67.6772 - mean_squared_error: 67.6772
Epoch 213/1000
331/331 [==============================] - 0s 60us/sample - loss: 67.6367 - mean_squared_error: 67.6367
Epoch 214/1000
331/331 [=======================

331/331 [==============================] - 0s 66us/sample - loss: 66.0432 - mean_squared_error: 66.0432
Epoch 275/1000
331/331 [==============================] - 0s 73us/sample - loss: 66.0169 - mean_squared_error: 66.0169
Epoch 276/1000
331/331 [==============================] - 0s 57us/sample - loss: 66.1078 - mean_squared_error: 66.1077
Epoch 277/1000
331/331 [==============================] - 0s 54us/sample - loss: 65.9680 - mean_squared_error: 65.9680
Epoch 278/1000
331/331 [==============================] - 0s 73us/sample - loss: 65.9750 - mean_squared_error: 65.9750
Epoch 279/1000
331/331 [==============================] - 0s 60us/sample - loss: 65.9245 - mean_squared_error: 65.9245
Epoch 280/1000
331/331 [==============================] - 0s 51us/sample - loss: 65.9029 - mean_squared_error: 65.9029
Epoch 281/1000
331/331 [==============================] - 0s 85us/sample - loss: 65.8812 - mean_squared_error: 65.8812
Epoch 282/1000
331/331 [==============================] - 0s 51

Epoch 343/1000
331/331 [==============================] - 0s 45us/sample - loss: 65.0062 - mean_squared_error: 65.0062
Epoch 344/1000
331/331 [==============================] - 0s 63us/sample - loss: 65.0065 - mean_squared_error: 65.0064
Epoch 345/1000
331/331 [==============================] - 0s 54us/sample - loss: 64.9922 - mean_squared_error: 64.9922
Epoch 346/1000
331/331 [==============================] - 0s 54us/sample - loss: 65.0240 - mean_squared_error: 65.0240
Epoch 347/1000
331/331 [==============================] - 0s 51us/sample - loss: 65.1574 - mean_squared_error: 65.1574
Epoch 348/1000
331/331 [==============================] - 0s 57us/sample - loss: 64.9828 - mean_squared_error: 64.9828
Epoch 349/1000
331/331 [==============================] - 0s 60us/sample - loss: 64.9873 - mean_squared_error: 64.9873
Epoch 350/1000
331/331 [==============================] - 0s 51us/sample - loss: 65.0183 - mean_squared_error: 65.0183
Epoch 351/1000
331/331 [========================

331/331 [==============================] - 0s 51us/sample - loss: 64.4455 - mean_squared_error: 64.4455
Epoch 412/1000
331/331 [==============================] - 0s 69us/sample - loss: 64.3728 - mean_squared_error: 64.3728
Epoch 413/1000
331/331 [==============================] - 0s 54us/sample - loss: 64.3821 - mean_squared_error: 64.3821
Epoch 414/1000
331/331 [==============================] - 0s 48us/sample - loss: 64.4788 - mean_squared_error: 64.4788
Epoch 415/1000
331/331 [==============================] - 0s 51us/sample - loss: 64.4521 - mean_squared_error: 64.4521
Epoch 416/1000
331/331 [==============================] - 0s 60us/sample - loss: 64.3848 - mean_squared_error: 64.3848
Epoch 417/1000
331/331 [==============================] - 0s 57us/sample - loss: 64.3867 - mean_squared_error: 64.3867
Epoch 418/1000
331/331 [==============================] - 0s 57us/sample - loss: 64.3095 - mean_squared_error: 64.3095
Epoch 419/1000
331/331 [==============================] - 0s 66

331/331 [==============================] - 0s 79us/sample - loss: 63.9452 - mean_squared_error: 63.9452
Epoch 480/1000
331/331 [==============================] - 0s 60us/sample - loss: 64.0263 - mean_squared_error: 64.0263
Epoch 481/1000
331/331 [==============================] - 0s 60us/sample - loss: 63.9019 - mean_squared_error: 63.9019
Epoch 482/1000
331/331 [==============================] - 0s 58us/sample - loss: 64.0806 - mean_squared_error: 64.0806
Epoch 483/1000
331/331 [==============================] - 0s 51us/sample - loss: 63.9023 - mean_squared_error: 63.9023
Epoch 484/1000
331/331 [==============================] - 0s 45us/sample - loss: 63.9626 - mean_squared_error: 63.9626
Epoch 485/1000
331/331 [==============================] - 0s 63us/sample - loss: 63.9426 - mean_squared_error: 63.9425
Epoch 486/1000
331/331 [==============================] - 0s 54us/sample - loss: 64.1121 - mean_squared_error: 64.1121
Epoch 487/1000
331/331 [==============================] - 0s 57

Epoch 548/1000
331/331 [==============================] - 0s 91us/sample - loss: 63.5096 - mean_squared_error: 63.5096
Epoch 549/1000
331/331 [==============================] - 0s 60us/sample - loss: 63.7027 - mean_squared_error: 63.7027
Epoch 550/1000
331/331 [==============================] - 0s 57us/sample - loss: 63.6199 - mean_squared_error: 63.6199
Epoch 551/1000
331/331 [==============================] - 0s 55us/sample - loss: 63.6348 - mean_squared_error: 63.6348
Epoch 552/1000
331/331 [==============================] - 0s 60us/sample - loss: 63.5728 - mean_squared_error: 63.5728
Epoch 553/1000
331/331 [==============================] - 0s 54us/sample - loss: 63.5355 - mean_squared_error: 63.5355
Epoch 554/1000
331/331 [==============================] - 0s 57us/sample - loss: 63.4913 - mean_squared_error: 63.4913
Epoch 555/1000
331/331 [==============================] - 0s 54us/sample - loss: 63.5828 - mean_squared_error: 63.5829
Epoch 556/1000
331/331 [========================

331/331 [==============================] - 0s 76us/sample - loss: 63.2518 - mean_squared_error: 63.2518
Epoch 617/1000
331/331 [==============================] - 0s 64us/sample - loss: 63.1693 - mean_squared_error: 63.1693
Epoch 618/1000
331/331 [==============================] - 0s 54us/sample - loss: 63.2212 - mean_squared_error: 63.2212
Epoch 619/1000
331/331 [==============================] - 0s 51us/sample - loss: 63.2120 - mean_squared_error: 63.2120
Epoch 620/1000
331/331 [==============================] - 0s 54us/sample - loss: 63.2139 - mean_squared_error: 63.2139
Epoch 621/1000
331/331 [==============================] - 0s 54us/sample - loss: 63.2831 - mean_squared_error: 63.2831
Epoch 622/1000
331/331 [==============================] - 0s 51us/sample - loss: 63.2854 - mean_squared_error: 63.2854
Epoch 623/1000
331/331 [==============================] - 0s 60us/sample - loss: 63.1584 - mean_squared_error: 63.1584
Epoch 624/1000
331/331 [==============================] - 0s 60

Epoch 685/1000
331/331 [==============================] - 0s 69us/sample - loss: 62.9672 - mean_squared_error: 62.9672
Epoch 686/1000
331/331 [==============================] - 0s 66us/sample - loss: 62.9782 - mean_squared_error: 62.9782
Epoch 687/1000
331/331 [==============================] - 0s 54us/sample - loss: 62.9559 - mean_squared_error: 62.9559
Epoch 688/1000
331/331 [==============================] - 0s 79us/sample - loss: 63.0736 - mean_squared_error: 63.0736
Epoch 689/1000
331/331 [==============================] - 0s 51us/sample - loss: 62.9466 - mean_squared_error: 62.9466
Epoch 690/1000
331/331 [==============================] - 0s 60us/sample - loss: 63.0673 - mean_squared_error: 63.0673
Epoch 691/1000
331/331 [==============================] - 0s 54us/sample - loss: 62.9532 - mean_squared_error: 62.9532
Epoch 692/1000
331/331 [==============================] - 0s 63us/sample - loss: 63.0427 - mean_squared_error: 63.0426
Epoch 693/1000
331/331 [========================

331/331 [==============================] - 0s 88us/sample - loss: 62.8240 - mean_squared_error: 62.8240
Epoch 754/1000
331/331 [==============================] - 0s 97us/sample - loss: 62.7696 - mean_squared_error: 62.7696
Epoch 755/1000
331/331 [==============================] - 0s 68us/sample - loss: 62.7452 - mean_squared_error: 62.7453
Epoch 756/1000
331/331 [==============================] - 0s 60us/sample - loss: 62.7706 - mean_squared_error: 62.7706
Epoch 757/1000
331/331 [==============================] - 0s 57us/sample - loss: 62.8498 - mean_squared_error: 62.8498
Epoch 758/1000
331/331 [==============================] - 0s 54us/sample - loss: 62.7624 - mean_squared_error: 62.7624
Epoch 759/1000
331/331 [==============================] - 0s 60us/sample - loss: 62.6977 - mean_squared_error: 62.6977
Epoch 760/1000
331/331 [==============================] - 0s 54us/sample - loss: 62.8518 - mean_squared_error: 62.8518
Epoch 761/1000
331/331 [==============================] - 0s 57

Epoch 822/1000
331/331 [==============================] - 0s 80us/sample - loss: 62.4114 - mean_squared_error: 62.4114
Epoch 823/1000
331/331 [==============================] - 0s 48us/sample - loss: 62.4733 - mean_squared_error: 62.4733
Epoch 824/1000
331/331 [==============================] - 0s 54us/sample - loss: 62.4789 - mean_squared_error: 62.4789
Epoch 825/1000
331/331 [==============================] - 0s 51us/sample - loss: 62.5367 - mean_squared_error: 62.5368
Epoch 826/1000
331/331 [==============================] - 0s 54us/sample - loss: 62.6620 - mean_squared_error: 62.6620
Epoch 827/1000
331/331 [==============================] - 0s 60us/sample - loss: 62.3796 - mean_squared_error: 62.3796
Epoch 828/1000
331/331 [==============================] - 0s 51us/sample - loss: 62.4005 - mean_squared_error: 62.4005
Epoch 829/1000
331/331 [==============================] - 0s 54us/sample - loss: 62.3583 - mean_squared_error: 62.3583
Epoch 830/1000
331/331 [========================

331/331 [==============================] - 0s 79us/sample - loss: 62.0937 - mean_squared_error: 62.0937
Epoch 891/1000
331/331 [==============================] - 0s 82us/sample - loss: 62.0487 - mean_squared_error: 62.0487
Epoch 892/1000
331/331 [==============================] - 0s 60us/sample - loss: 62.1335 - mean_squared_error: 62.1335
Epoch 893/1000
331/331 [==============================] - 0s 45us/sample - loss: 61.9732 - mean_squared_error: 61.9732
Epoch 894/1000
331/331 [==============================] - 0s 69us/sample - loss: 62.1284 - mean_squared_error: 62.1284
Epoch 895/1000
331/331 [==============================] - 0s 63us/sample - loss: 62.1705 - mean_squared_error: 62.1705
Epoch 896/1000
331/331 [==============================] - 0s 51us/sample - loss: 62.0302 - mean_squared_error: 62.0302
Epoch 897/1000
331/331 [==============================] - 0s 73us/sample - loss: 62.0435 - mean_squared_error: 62.0435
Epoch 898/1000
331/331 [==============================] - 0s 60

Epoch 959/1000
331/331 [==============================] - 0s 79us/sample - loss: 61.6902 - mean_squared_error: 61.6902
Epoch 960/1000
331/331 [==============================] - 0s 70us/sample - loss: 61.6439 - mean_squared_error: 61.6439
Epoch 961/1000
331/331 [==============================] - 0s 79us/sample - loss: 61.6148 - mean_squared_error: 61.6148
Epoch 962/1000
331/331 [==============================] - 0s 66us/sample - loss: 61.7363 - mean_squared_error: 61.7363
Epoch 963/1000
331/331 [==============================] - 0s 51us/sample - loss: 61.7292 - mean_squared_error: 61.7292
Epoch 964/1000
331/331 [==============================] - 0s 63us/sample - loss: 61.6572 - mean_squared_error: 61.6572
Epoch 965/1000
331/331 [==============================] - 0s 60us/sample - loss: 61.6647 - mean_squared_error: 61.6647
Epoch 966/1000
331/331 [==============================] - 0s 54us/sample - loss: 61.6295 - mean_squared_error: 61.6295
Epoch 967/1000
331/331 [========================

In [22]:
ypred=ann.predict(x_test)

In [23]:
ypred

array([[44.169292],
       [18.310415],
       [43.26484 ],
       [17.768705],
       [49.603592],
       [36.20034 ],
       [40.067245],
       [36.91851 ],
       [49.846283],
       [47.83159 ],
       [43.689854],
       [36.061756],
       [43.858387],
       [38.684273],
       [49.04525 ],
       [39.320793],
       [35.632793],
       [45.936783],
       [36.671204],
       [41.999546],
       [51.257378],
       [25.964235],
       [34.280907],
       [48.13237 ],
       [46.905746],
       [40.431953],
       [42.090504],
       [21.61968 ],
       [49.200268],
       [18.692986],
       [43.364777],
       [34.303257],
       [45.923317],
       [43.306374],
       [39.394947],
       [26.861052],
       [48.055305],
       [33.21503 ],
       [48.696262],
       [22.616047],
       [48.07887 ],
       [33.495026],
       [27.189066],
       [50.60971 ],
       [20.471365],
       [37.56222 ],
       [36.11689 ],
       [19.693087],
       [29.307943],
       [47.28467 ],


In [24]:
y_test

array([45.3, 14.4, 46. , 15.6, 50.2, 38.1, 48.5, 41.4, 51.6, 40.1, 42. ,
       42.4, 28.5, 39.1, 53.7, 36.8, 40.6, 55.2, 39.3, 44.3, 53.5, 25.3,
       22.8, 51.7, 45.5, 34.4, 31.6, 25.9, 49.5, 24.7, 51.7, 29.7, 45.4,
       50.5, 26.5, 30.1, 46.1, 28.9, 54.4, 15. , 44.9, 29.8, 23.6, 48. ,
       16.7, 40.9, 40.2, 12.9, 21.3, 62.1, 63.9, 40.3, 42.2, 19.1, 28.4,
       28.5, 60.7, 37.5, 39.3, 28.8, 42.3, 44.3, 42.6, 57.4, 42.2, 25.7,
       13.2, 27. , 56.2, 38.3, 20.8, 43.1, 78.3, 20.9, 32.5, 33.4, 32.1,
       19.2, 53. , 38.2, 46.7, 24.6, 36.2])

In [25]:
data.head()

No  X1 transaction date  X2 house age  \
0   1             2012.917          32.0   
1   2             2012.917          19.5   
2   3             2013.583          13.3   
3   4             2013.500          13.3   
4   5             2012.833           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1

In [26]:
yy=ann.predict(sc.transform([[2012.917,32.0,84.87882,10,24.98298,121.54024]]))

In [27]:
yy

array([[47.04841]], dtype=float32)

In [28]:
ann.predict(sc.transform([[2012.917,19.5,306.5947,9,24.98034,121.53951]]))

array([[44.089764]], dtype=float32)

In [29]:
ann.predict(sc.transform([[2013.500,13.3,561.98450,5,24.98746,121.54391]]))

array([[50.29381]], dtype=float32)