In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("Prostate_Cancer.csv")

In [3]:
dataset.head(5)

id diagnosis_result  radius  texture  perimeter  area  smoothness  \
0   1                M      23       12        151   954       0.143   
1   2                B       9       13        133  1326       0.143   
2   3                M      21       27        130  1203       0.125   
3   4                M      14       16         78   386       0.070   
4   5                M       9       19        135  1297       0.141   

   compactness  symmetry  fractal_dimension  
0        0.278     0.242              0.079  
1        0.079     0.181              0.057  
2        0.160     0.207              0.060  
3        0.284     0.260              0.097  
4        0.133     0.181              0.059

In [4]:
dataset.isnull().sum()

id                   0
diagnosis_result     0
radius               0
texture              0
perimeter            0
area                 0
smoothness           0
compactness          0
symmetry             0
fractal_dimension    0
dtype: int64

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
id                   100 non-null int64
diagnosis_result     100 non-null object
radius               100 non-null int64
texture              100 non-null int64
perimeter            100 non-null int64
area                 100 non-null int64
smoothness           100 non-null float64
compactness          100 non-null float64
symmetry             100 non-null float64
fractal_dimension    100 non-null float64
dtypes: float64(4), int64(5), object(1)
memory usage: 7.9+ KB


In [6]:
x=dataset.iloc[:,2:10].values
y=dataset.iloc[:,1:2].values

In [7]:
x

array([[2.300e+01, 1.200e+01, 1.510e+02, 9.540e+02, 1.430e-01, 2.780e-01,
        2.420e-01, 7.900e-02],
       [9.000e+00, 1.300e+01, 1.330e+02, 1.326e+03, 1.430e-01, 7.900e-02,
        1.810e-01, 5.700e-02],
       [2.100e+01, 2.700e+01, 1.300e+02, 1.203e+03, 1.250e-01, 1.600e-01,
        2.070e-01, 6.000e-02],
       [1.400e+01, 1.600e+01, 7.800e+01, 3.860e+02, 7.000e-02, 2.840e-01,
        2.600e-01, 9.700e-02],
       [9.000e+00, 1.900e+01, 1.350e+02, 1.297e+03, 1.410e-01, 1.330e-01,
        1.810e-01, 5.900e-02],
       [2.500e+01, 2.500e+01, 8.300e+01, 4.770e+02, 1.280e-01, 1.700e-01,
        2.090e-01, 7.600e-02],
       [1.600e+01, 2.600e+01, 1.200e+02, 1.040e+03, 9.500e-02, 1.090e-01,
        1.790e-01, 5.700e-02],
       [1.500e+01, 1.800e+01, 9.000e+01, 5.780e+02, 1.190e-01, 1.650e-01,
        2.200e-01, 7.500e-02],
       [1.900e+01, 2.400e+01, 8.800e+01, 5.200e+02, 1.270e-01, 1.930e-01,
        2.350e-01, 7.400e-02],
       [2.500e+01, 1.100e+01, 8.400e+01, 4.760e+02, 1.1

In [8]:
y

array([['M'],
       ['B'],
       ['M'],
       ['M'],
       ['M'],
       ['B'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['B'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['B'],
       ['B'],
       ['B'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['B'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['M'],
       ['B'],
       ['M'],
       ['B'],
       ['B'],
       ['B'],
       ['B'],
       ['B'],
       ['M'],
       ['M'],
       ['B'],
       ['M'],
       ['M'],
       ['B'],
       ['B'],
       ['B'],
       ['B'],
       ['M'],
       ['B'],
       ['M'],
       ['M'],
       ['B'],
       ['B'],
       ['B'],
       ['B'],
       ['M'],
      

In [9]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[0])],remainder="passthrough")
#coverts data into binary form

y=ct.fit_transform(y)

In [10]:
y.shape

(100, 2)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0) #test_size=0.2 is 20% testing data

In [14]:
x_train = np.asarray(x_train).astype('float32')
x_test = np.asarray(x_test).astype('float32')
y_train = np.asarray(y_train).astype('float32')
y_test = np.asarray(y_test).astype('float32')

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [16]:
from tensorflow.keras.models import Sequential #used to initialize
from tensorflow.keras.layers import Dense #used to add layers

In [17]:
cat=Sequential()

In [18]:
cat.add(Dense(8,kernel_initializer ="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [19]:
cat.add(Dense(16,kernel_initializer ="random_uniform",activation="relu"))

In [20]:
cat.add(Dense(2,kernel_initializer ="random_uniform",activation="softmax"))

In [21]:
cat.compile("adam","binary_crossentropy",metrics=["accuracy"]) #nick name for batch gradient is adam.

In [22]:
cat.fit(x_train,y_train,batch_size=32,epochs=20)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/20
80/80 [==============================] - 0s 5ms/sample - loss: 0.6930 - acc: 0.6000
Epoch 2/20
80/80 [==============================] - 0s 249us/sample - loss: 0.6925 - acc: 0.5625
Epoch 3/20
80/80 [==============================] - 0s 187us/sample - loss: 0.6921 - acc: 0.5625
Epoch 4/20
80/80 [==============================] - 0s 283us/sample - loss: 0.6917 - acc: 0.5625
Epoch 5/20
80/80 [==============================] - 0s 253us/sample - loss: 0.6913 - acc: 0.5625
Epoch 6/20
80/80 [==============================] - 0s 212us/sample - loss: 0.6908 - acc: 0.5625
Epoch 7/20
80/80 [==============================] - 0s 243us/sample - loss: 0.6901 - acc: 0.5625
Epoch 8/20
80/80 [==============================] - 0s 187us/sample - loss: 0.6894 - acc: 0.5625
Epoch 9/20
80/80 [==============================] - 0s 199us/sample - loss: 0.6886 - acc: 0.5625
Epoch 10/20
80/80 [================

In [24]:
ypred=cat.predict(x_test)

In [25]:
ypred

array([[0.48082328, 0.5191768 ],
       [0.5093831 , 0.49061698],
       [0.45441368, 0.54558635],
       [0.5257996 , 0.47420043],
       [0.5079073 , 0.49209276],
       [0.5059938 , 0.49400625],
       [0.5013097 , 0.49869025],
       [0.517953  , 0.48204708],
       [0.5162394 , 0.4837606 ],
       [0.4522826 , 0.54771745],
       [0.46000782, 0.5399921 ],
       [0.5255053 , 0.4744947 ],
       [0.42841074, 0.57158923],
       [0.49183652, 0.50816345],
       [0.4930819 , 0.50691813],
       [0.4489058 , 0.55109423],
       [0.4777801 , 0.5222199 ],
       [0.45846435, 0.54153574],
       [0.44761735, 0.55238265],
       [0.49384293, 0.50615716]], dtype=float32)

In [26]:
y_test

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [33]:
dataset.head(10)

id diagnosis_result  radius  texture  perimeter  area  smoothness  \
0   1                M      23       12        151   954       0.143   
1   2                B       9       13        133  1326       0.143   
2   3                M      21       27        130  1203       0.125   
3   4                M      14       16         78   386       0.070   
4   5                M       9       19        135  1297       0.141   
5   6                B      25       25         83   477       0.128   
6   7                M      16       26        120  1040       0.095   
7   8                M      15       18         90   578       0.119   
8   9                M      19       24         88   520       0.127   
9  10                M      25       11         84   476       0.119   

   compactness  symmetry  fractal_dimension  
0        0.278     0.242              0.079  
1        0.079     0.181              0.057  
2        0.160     0.207              0.060  
3        0.284     0.260              0.097  
4        0.133     0.181              0.059  
5        0.170     0.209              0.076  
6        0.109     0.179              0.057  
7        0.165     0.220              0.075  
8        0.193     0.235              0.074  
9        0.240     0.203              0.082

In [29]:
yp=cat.predict_classes(sc.transform([[23,12,151,954,0.143,0.278,0.242,0.079]]))

In [30]:
yp

array([1], dtype=int64)

In [31]:
yp=cat.predict_classes(sc.transform([[9,13,133,1326,0.143,0.079,0.181,0.057]]))

In [32]:
yp

array([1], dtype=int64)

In [34]:
yp=cat.predict_classes(sc.transform([[25,25,83,477,0.128,0.170,0.209,0.076]]))

In [35]:
yp

array([0], dtype=int64)