In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv(r"D:\geethanjaliexternship\source files\heart.csv")

In [3]:
dataset.head(10)

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   
5   57    1   0     140   192    0        1       148     0      0.4    1   
6   56    0   1     140   294    0        0       153     0      1.3    1   
7   44    1   1     120   263    0        1       173     0      0.0    2   
8   52    1   2     172   199    1        1       162     0      0.5    2   
9   57    1   2     150   168    0        1       174     0      1.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1  
5    0      1       1  
6    0      2       1  
7    0      3       1  
8    0      3       1  
9    0      2       1

In [4]:
dataset.isnull().any()

age         False
sex         False
cp          False
trtbps      False
chol        False
fbs         False
restecg     False
thalachh    False
exng        False
oldpeak     False
slp         False
caa         False
thall       False
output      False
dtype: bool

In [9]:
x = dataset.iloc[:,0:13].values
y = dataset.iloc[:,13].values

In [10]:
x

array([[63.,  1.,  3., ...,  0.,  0.,  1.],
       [37.,  1.,  2., ...,  0.,  0.,  2.],
       [41.,  0.,  1., ...,  2.,  0.,  2.],
       ...,
       [68.,  1.,  0., ...,  1.,  2.,  3.],
       [57.,  1.,  0., ...,  1.,  1.,  3.],
       [57.,  0.,  1., ...,  1.,  1.,  2.]])

In [11]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2 , random_state = 0)

In [13]:
x_train.shape

(242, 13)

In [14]:
x_test.shape

(61, 13)

In [15]:
y_train.shape

(242,)

In [17]:
y_test.shape

(61,)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [21]:
bnn = Sequential()

In [23]:
bnn.add(Dense(13,kernel_initializer="random_uniform",activation = "relu"))

In [26]:
bnn.add(Dense(26,kernel_initializer = "random_uniform",activation = "relu"))

In [27]:
bnn.add(Dense(1,kernel_initializer = "random_uniform" ,activation = "sigmoid" ))

In [31]:
bnn.compile("adam" , "binary_crossentropy",metrics=["accuracy"])

In [32]:
bnn.fit(x_train,y_train,batch_size = 32 , epochs = 100)

Epoch 1/100
8/8 [==============================] - 1s 3ms/step - loss: 0.6935 - accuracy: 0.4974
Epoch 2/100
8/8 [==============================] - 0s 3ms/step - loss: 0.6930 - accuracy: 0.5001
Epoch 3/100
8/8 [==============================] - 0s 3ms/step - loss: 0.6917 - accuracy: 0.5864
Epoch 4/100
8/8 [==============================] - 0s 3ms/step - loss: 0.6922 - accuracy: 0.5299
Epoch 5/100
8/8 [==============================] - 0s 3ms/step - loss: 0.6919 - accuracy: 0.5307
Epoch 6/100
8/8 [==============================] - 0s 3ms/step - loss: 0.6903 - accuracy: 0.5533
Epoch 7/100
8/8 [==============================] - 0s 3ms/step - loss: 0.6894 - accuracy: 0.5537
Epoch 8/100
8/8 [==============================] - 0s 3ms/step - loss: 0.6891 - accuracy: 0.5446
Epoch 9/100
8/8 [==============================] - 0s 2ms/step - loss: 0.6884 - accuracy: 0.5404
Epoch 10/100
8/8 [==============================] - 0s 3ms/step - loss: 0.6892 - accuracy: 0.5214
Epoch 11/100
8/8 [===========

8/8 [==============================] - 0s 3ms/step - loss: 0.3282 - accuracy: 0.8682
Epoch 85/100
8/8 [==============================] - 0s 2ms/step - loss: 0.3052 - accuracy: 0.8860
Epoch 86/100
8/8 [==============================] - 0s 3ms/step - loss: 0.3114 - accuracy: 0.8844
Epoch 87/100
8/8 [==============================] - 0s 3ms/step - loss: 0.2864 - accuracy: 0.8987
Epoch 88/100
8/8 [==============================] - 0s 2ms/step - loss: 0.2672 - accuracy: 0.8956
Epoch 89/100
8/8 [==============================] - 0s 3ms/step - loss: 0.3078 - accuracy: 0.8826
Epoch 90/100
8/8 [==============================] - 0s 3ms/step - loss: 0.2577 - accuracy: 0.9132
Epoch 91/100
8/8 [==============================] - 0s 2ms/step - loss: 0.2974 - accuracy: 0.8954
Epoch 92/100
8/8 [==============================] - 0s 3ms/step - loss: 0.2896 - accuracy: 0.9033
Epoch 93/100
8/8 [==============================] - 0s 3ms/step - loss: 0.2960 - accuracy: 0.8850
Epoch 94/100
8/8 [===============

In [34]:
ypred = bnn.predict(x_test)

In [37]:
ypred<0.5

array([[ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False]])

In [36]:
y_test

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1], dtype=int64)

In [38]:
dataset.head(1)

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   

   caa  thall  output  
0    0      1       1

In [39]:
bnn.predict_classes(sc.transform([[40,1,3,222,44,1,0,332,1,1.2,1,0,1]]))

C:\Users\heart\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[1]])