In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("Bank_Personal_Loan_Modelling.csv")

In [3]:
dataset.head(5)

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [4]:
dataset.isnull().sum()

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
ID                    5000 non-null int64
Age                   5000 non-null int64
Experience            5000 non-null int64
Income                5000 non-null int64
ZIP Code              5000 non-null int64
Family                5000 non-null int64
CCAvg                 5000 non-null float64
Education             5000 non-null int64
Mortgage              5000 non-null int64
Personal Loan         5000 non-null int64
Securities Account    5000 non-null int64
CD Account            5000 non-null int64
Online                5000 non-null int64
CreditCard            5000 non-null int64
dtypes: float64(1), int64(13)
memory usage: 547.0 KB


In [6]:
dataset.drop(columns=["ID","ZIP Code"],inplace=True)

In [7]:
dataset.head()

Age  Experience  Income  Family  CCAvg  Education  Mortgage  Personal Loan  \
0   25           1      49       4    1.6          1         0              0   
1   45          19      34       3    1.5          1         0              0   
2   39          15      11       1    1.0          1         0              0   
3   35           9     100       1    2.7          2         0              0   
4   35           8      45       4    1.0          2         0              0   

   Securities Account  CD Account  Online  CreditCard  
0                   1           0       0           0  
1                   1           0       0           0  
2                   0           0       0           0  
3                   0           0       0           0  
4                   0           0       0           1

In [8]:
x=dataset.iloc[:,[0,1,2,3,4,5,6,8,9,10,11]].values
y=dataset.iloc[:,7].values

In [9]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [10]:
x

array([[25.,  1., 49., ...,  0.,  0.,  0.],
       [45., 19., 34., ...,  0.,  0.,  0.],
       [39., 15., 11., ...,  0.,  0.,  0.],
       ...,
       [63., 39., 24., ...,  0.,  0.,  0.],
       [65., 40., 49., ...,  0.,  1.,  0.],
       [28.,  4., 83., ...,  0.,  1.,  1.]])

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0) #test_size=0.2 is 20% testing data

In [12]:
x_train.shape

(4000, 11)

In [13]:
x_test.shape

(1000, 11)

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [15]:
from tensorflow.keras.models import Sequential #used to initialize
from tensorflow.keras.layers import Dense #used to add layers

In [16]:
ann=Sequential()

In [17]:
ann.add(Dense(11,kernel_initializer ="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [18]:
ann.add(Dense(22,kernel_initializer ="random_uniform",activation="relu"))

In [19]:
ann.add(Dense(1,kernel_initializer ="random_uniform",activation="sigmoid"))

In [20]:
ann.compile("adam","binary_crossentropy",metrics=["accuracy"]) #nick name for batch gradient is adam.

In [21]:
ann.fit(x_train,y_train,batch_size=32,epochs=30)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/30
4000/4000 [==============================] - 1s 236us/sample - loss: 0.5112 - acc: 0.9022
Epoch 2/30
4000/4000 [==============================] - 0s 74us/sample - loss: 0.1991 - acc: 0.9025
Epoch 3/30
4000/4000 [==============================] - 0s 68us/sample - loss: 0.1623 - acc: 0.9025
Epoch 4/30
4000/4000 [==============================] - 0s 70us/sample - loss: 0.1403 - acc: 0.9025
Epoch 5/30
4000/4000 [==============================] - 0s 74us/sample - loss: 0.1253 - acc: 0.9025
Epoch 6/30
4000/4000 [==============================] - 0s 64us/sample - loss: 0.1191 - acc: 0.9270
Epoch 7/30
4000/4000 [==============================] - 0s 64us/sample - loss: 0.1149 - acc: 0.9640
Epoch 8/30
4000/4000 [==============================] - 0s 66us/sample - loss: 0.1112 - acc: 0.9690
Epoch 9/30
4000/4000 [==============================] - 0s 62us/sample - loss: 0.1077 - acc: 0.9697
Epoch

In [22]:
ypred=ann.predict(x_test)

In [23]:
ypred

array([[0.00000000e+00],
       [1.19209290e-07],
       [3.88920307e-05],
       [5.83440065e-04],
       [4.00510430e-02],
       [4.47034836e-07],
       [7.80197918e-01],
       [7.80197918e-01],
       [7.97213316e-02],
       [0.00000000e+00],
       [1.90734863e-06],
       [4.68677282e-03],
       [0.00000000e+00],
       [3.25185061e-03],
       [1.26422763e-01],
       [4.20951843e-03],
       [0.00000000e+00],
       [1.52885914e-05],
       [0.00000000e+00],
       [9.38832760e-04],
       [0.00000000e+00],
       [0.00000000e+00],
       [9.06412899e-02],
       [7.80197918e-01],
       [0.00000000e+00],
       [1.49011612e-07],
       [7.80197918e-01],
       [7.80197918e-01],
       [0.00000000e+00],
       [2.58088112e-05],
       [2.51829624e-05],
       [0.00000000e+00],
       [2.75343657e-04],
       [3.76403332e-05],
       [3.02433968e-04],
       [3.38256359e-05],
       [5.63561916e-05],
       [1.24424696e-04],
       [2.72810459e-04],
       [1.58846378e-03],


In [24]:
y_test

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,

In [25]:
dataset.head(10)

Age  Experience  Income  Family  CCAvg  Education  Mortgage  Personal Loan  \
0   25           1      49       4    1.6          1         0              0   
1   45          19      34       3    1.5          1         0              0   
2   39          15      11       1    1.0          1         0              0   
3   35           9     100       1    2.7          2         0              0   
4   35           8      45       4    1.0          2         0              0   
5   37          13      29       4    0.4          2       155              0   
6   53          27      72       2    1.5          2         0              0   
7   50          24      22       1    0.3          3         0              0   
8   35          10      81       3    0.6          2       104              0   
9   34           9     180       1    8.9          3         0              1   

   Securities Account  CD Account  Online  CreditCard  
0                   1           0       0           0  
1                   1           0       0           0  
2                   0           0       0           0  
3                   0           0       0           0  
4                   0           0       0           1  
5                   0           0       1           0  
6                   0           0       1           0  
7                   0           0       0           1  
8                   0           0       1           0  
9                   0           0       0           0

In [26]:
ann.predict_classes(sc.transform([[25,1,49,4,1.6,1,0,1,0,0,0]]))

array([[0]])

In [27]:
ann.predict_classes(sc.transform([[45,19,34,3,1.5,1,0,1,0,0,0]]))

array([[0]])

In [28]:
ann.predict_classes(sc.transform([[34,9,180,1,8.9,3,0,0,0,0,0]]))

array([[1]])

In [29]:
ypred>0.5

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [

In [30]:
yp=ann.predict_classes(sc.transform([[34,9,180,1,8.9,3,0,0,0,0,0]]))

In [31]:
yp>0.5

array([[ True]])