In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("continent.csv")

In [3]:
dataset.head()

name  Longitude   Latitude      continent
0        Aruba -69.982677  12.520880  North America
1  Afghanistan  66.004734  33.835231           Asia
2       Angola  17.537368 -12.293361         Africa
3     Anguilla -63.064989  18.223959  North America
4      Albania  20.049834  41.142450         Europe

In [4]:
dataset.isnull().sum()

name         0
Longitude    0
Latitude     0
continent    0
dtype: int64

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 4 columns):
name         241 non-null object
Longitude    241 non-null float64
Latitude     241 non-null float64
continent    241 non-null object
dtypes: float64(2), object(2)
memory usage: 7.6+ KB


In [6]:
dataset["continent"].unique()  #0,1,2

array(['North America', 'Asia', 'Africa', 'Europe', 'South America',
       'Oceania', 'Antarctica', 'Seven seas (open ocean)'], dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset["name"]=le.fit_transform(dataset["name"])

In [8]:
x=dataset.iloc[:,0:3].values
y=dataset.iloc[:,3:4].values

In [9]:
x

array([[  12.        ,  -69.98267711,   12.52088038],
       [   0.        ,   66.00473366,   33.83523073],
       [   6.        ,   17.53736768,  -12.29336054],
       [   7.        ,  -63.06498927,   18.2239595 ],
       [   2.        ,   20.04983396,   41.14244989],
       [   1.        ,   19.95328768,   60.21488688],
       [   5.        ,    1.56054378,   42.54229102],
       [ 227.        ,   54.3001671 ,   23.90528188],
       [  10.        ,  -65.17980692,  -35.3813488 ],
       [  11.        ,   44.92993276,   40.28952569],
       [   4.        , -170.7180258 ,  -14.30445997],
       [   8.        ,   19.92108951,  -80.50857913],
       [  13.        ,  123.5838379 ,  -12.42993164],
       [  75.        ,   69.22666758,  -49.24895485],
       [   9.        ,  -61.79469343,   17.2774996 ],
       [  14.        ,  134.4910001 ,  -25.73288704],
       [  15.        ,   14.1264761 ,   47.58549439],
       [  16.        ,   47.54599879,   40.28827235],
       [  36.        ,   29.

In [10]:
y

array([['North America'],
       ['Asia'],
       ['Africa'],
       ['North America'],
       ['Europe'],
       ['Europe'],
       ['Europe'],
       ['Asia'],
       ['South America'],
       ['Asia'],
       ['Oceania'],
       ['Antarctica'],
       ['Oceania'],
       ['Seven seas (open ocean)'],
       ['North America'],
       ['Oceania'],
       ['Europe'],
       ['Asia'],
       ['Africa'],
       ['Europe'],
       ['Africa'],
       ['Africa'],
       ['Asia'],
       ['Europe'],
       ['Asia'],
       ['North America'],
       ['North America'],
       ['Europe'],
       ['North America'],
       ['Europe'],
       ['North America'],
       ['North America'],
       ['South America'],
       ['South America'],
       ['North America'],
       ['Asia'],
       ['Asia'],
       ['Africa'],
       ['Africa'],
       ['Europe'],
       ['South America'],
       ['Asia'],
       ['Africa'],
       ['Africa'],
       ['Africa'],
       ['Africa'],
       ['Oceania'],
       ['

In [11]:
x.shape

(241, 3)

In [12]:
y.shape

(241, 1)

In [14]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
one=OneHotEncoder()
z=one.fit_transform(y[:,0:1]).toarray()
y=np.delete(y,0,axis=1)
y=np.concatenate((z,y),axis=1)

In [15]:
y.shape

(241, 8)

In [16]:
x.shape

(241, 3)

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=4) #test_size=0.2 is 20% testing data

In [27]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [28]:
from tensorflow.keras.models import Sequential #used to initialize
from tensorflow.keras.layers import Dense #used to add layers

In [29]:
ann=Sequential()

In [30]:
ann.add(Dense(3,kernel_initializer ="random_uniform",activation="relu"))

In [31]:
ann.add(Dense(6,kernel_initializer ="random_uniform",activation="relu"))

In [32]:
ann.add(Dense(8,kernel_initializer ="random_uniform",activation="softmax"))

In [33]:
ann.compile("adam","categorical_crossentropy",metrics=["accuracy"]) #nick name for batch gradient is adam.

In [34]:
ann.fit(x_train,y_train,batch_size=32,epochs=1000)

Epoch 1/1000
192/192 [==============================] - 0s 641us/sample - loss: 2.0780 - acc: 0.2135
Epoch 2/1000
192/192 [==============================] - 0s 52us/sample - loss: 2.0746 - acc: 0.2188
Epoch 3/1000
192/192 [==============================] - 0s 52us/sample - loss: 2.0710 - acc: 0.2188
Epoch 4/1000
192/192 [==============================] - 0s 85us/sample - loss: 2.0673 - acc: 0.2188
Epoch 5/1000
192/192 [==============================] - 0s 78us/sample - loss: 2.0635 - acc: 0.2188
Epoch 6/1000
192/192 [==============================] - 0s 68us/sample - loss: 2.0594 - acc: 0.2188
Epoch 7/1000
192/192 [==============================] - 0s 78us/sample - loss: 2.0548 - acc: 0.2240
Epoch 8/1000
192/192 [==============================] - 0s 93us/sample - loss: 2.0503 - acc: 0.2917
Epoch 9/1000
192/192 [==============================] - 0s 52us/sample - loss: 2.0450 - acc: 0.2240
Epoch 10/1000
192/192 [==============================] - 0s 81us/sample - loss: 2.0392 - acc: 0.218

192/192 [==============================] - 0s 57us/sample - loss: 1.4863 - acc: 0.3281
Epoch 83/1000
192/192 [==============================] - 0s 65us/sample - loss: 1.4838 - acc: 0.3385
Epoch 84/1000
192/192 [==============================] - 0s 62us/sample - loss: 1.4812 - acc: 0.3385
Epoch 85/1000
192/192 [==============================] - 0s 42us/sample - loss: 1.4786 - acc: 0.3385
Epoch 86/1000
192/192 [==============================] - 0s 52us/sample - loss: 1.4760 - acc: 0.3333
Epoch 87/1000
192/192 [==============================] - 0s 125us/sample - loss: 1.4735 - acc: 0.3333
Epoch 88/1000
192/192 [==============================] - 0s 62us/sample - loss: 1.4708 - acc: 0.3333
Epoch 89/1000
192/192 [==============================] - 0s 83us/sample - loss: 1.4685 - acc: 0.3385
Epoch 90/1000
192/192 [==============================] - 0s 68us/sample - loss: 1.4661 - acc: 0.3438
Epoch 91/1000
192/192 [==============================] - 0s 62us/sample - loss: 1.4638 - acc: 0.3490
Epo

192/192 [==============================] - 0s 62us/sample - loss: 1.3229 - acc: 0.4896
Epoch 163/1000
192/192 [==============================] - 0s 57us/sample - loss: 1.3210 - acc: 0.4948
Epoch 164/1000
192/192 [==============================] - 0s 52us/sample - loss: 1.3194 - acc: 0.5000
Epoch 165/1000
192/192 [==============================] - 0s 52us/sample - loss: 1.3176 - acc: 0.5000
Epoch 166/1000
192/192 [==============================] - 0s 73us/sample - loss: 1.3161 - acc: 0.5000
Epoch 167/1000
192/192 [==============================] - 0s 78us/sample - loss: 1.3144 - acc: 0.5000
Epoch 168/1000
192/192 [==============================] - 0s 69us/sample - loss: 1.3129 - acc: 0.5000
Epoch 169/1000
192/192 [==============================] - 0s 78us/sample - loss: 1.3113 - acc: 0.5000
Epoch 170/1000
192/192 [==============================] - 0s 78us/sample - loss: 1.3096 - acc: 0.5000
Epoch 171/1000
192/192 [==============================] - 0s 109us/sample - loss: 1.3082 - acc: 0

192/192 [==============================] - 0s 52us/sample - loss: 1.2128 - acc: 0.5156
Epoch 243/1000
192/192 [==============================] - 0s 57us/sample - loss: 1.2117 - acc: 0.5156
Epoch 244/1000
192/192 [==============================] - 0s 52us/sample - loss: 1.2104 - acc: 0.5156
Epoch 245/1000
192/192 [==============================] - 0s 47us/sample - loss: 1.2095 - acc: 0.5156
Epoch 246/1000
192/192 [==============================] - 0s 62us/sample - loss: 1.2084 - acc: 0.5156
Epoch 247/1000
192/192 [==============================] - 0s 47us/sample - loss: 1.2070 - acc: 0.5156
Epoch 248/1000
192/192 [==============================] - 0s 52us/sample - loss: 1.2061 - acc: 0.5156
Epoch 249/1000
192/192 [==============================] - ETA: 0s - loss: 1.2372 - acc: 0.531 - 0s 57us/sample - loss: 1.2046 - acc: 0.5156
Epoch 250/1000
192/192 [==============================] - 0s 73us/sample - loss: 1.2035 - acc: 0.5156
Epoch 251/1000
192/192 [==============================] - 0

192/192 [==============================] - 0s 57us/sample - loss: 1.1225 - acc: 0.5573
Epoch 323/1000
192/192 [==============================] - 0s 52us/sample - loss: 1.1210 - acc: 0.5625
Epoch 324/1000
192/192 [==============================] - 0s 47us/sample - loss: 1.1199 - acc: 0.5573
Epoch 325/1000
192/192 [==============================] - 0s 57us/sample - loss: 1.1188 - acc: 0.5573
Epoch 326/1000
192/192 [==============================] - 0s 57us/sample - loss: 1.1174 - acc: 0.5625
Epoch 327/1000
192/192 [==============================] - 0s 62us/sample - loss: 1.1162 - acc: 0.5729
Epoch 328/1000
192/192 [==============================] - 0s 78us/sample - loss: 1.1152 - acc: 0.5729
Epoch 329/1000
192/192 [==============================] - 0s 68us/sample - loss: 1.1141 - acc: 0.5729
Epoch 330/1000
192/192 [==============================] - 0s 57us/sample - loss: 1.1134 - acc: 0.5729
Epoch 331/1000
192/192 [==============================] - 0s 52us/sample - loss: 1.1116 - acc: 0.

192/192 [==============================] - 0s 57us/sample - loss: 1.0232 - acc: 0.6094
Epoch 403/1000
192/192 [==============================] - 0s 57us/sample - loss: 1.0215 - acc: 0.6042
Epoch 404/1000
192/192 [==============================] - 0s 62us/sample - loss: 1.0200 - acc: 0.6094
Epoch 405/1000
192/192 [==============================] - 0s 66us/sample - loss: 1.0190 - acc: 0.6042
Epoch 406/1000
192/192 [==============================] - 0s 73us/sample - loss: 1.0173 - acc: 0.6042
Epoch 407/1000
192/192 [==============================] - 0s 57us/sample - loss: 1.0161 - acc: 0.6042
Epoch 408/1000
192/192 [==============================] - 0s 68us/sample - loss: 1.0149 - acc: 0.6094
Epoch 409/1000
192/192 [==============================] - 0s 73us/sample - loss: 1.0131 - acc: 0.6146
Epoch 410/1000
192/192 [==============================] - 0s 57us/sample - loss: 1.0120 - acc: 0.6146
Epoch 411/1000
192/192 [==============================] - 0s 47us/sample - loss: 1.0104 - acc: 0.

192/192 [==============================] - 0s 57us/sample - loss: 0.8792 - acc: 0.6667
Epoch 482/1000
192/192 [==============================] - 0s 52us/sample - loss: 0.8777 - acc: 0.6667
Epoch 483/1000
192/192 [==============================] - 0s 57us/sample - loss: 0.8755 - acc: 0.6667
Epoch 484/1000
192/192 [==============================] - 0s 47us/sample - loss: 0.8745 - acc: 0.6667
Epoch 485/1000
192/192 [==============================] - 0s 53us/sample - loss: 0.8728 - acc: 0.6667
Epoch 486/1000
192/192 [==============================] - 0s 62us/sample - loss: 0.8706 - acc: 0.6667
Epoch 487/1000
192/192 [==============================] - 0s 73us/sample - loss: 0.8689 - acc: 0.6667
Epoch 488/1000
192/192 [==============================] - 0s 88us/sample - loss: 0.8681 - acc: 0.6771
Epoch 489/1000
192/192 [==============================] - 0s 78us/sample - loss: 0.8656 - acc: 0.6823
Epoch 490/1000
192/192 [==============================] - 0s 52us/sample - loss: 0.8638 - acc: 0.

192/192 [==============================] - 0s 68us/sample - loss: 0.7639 - acc: 0.7188
Epoch 562/1000
192/192 [==============================] - 0s 57us/sample - loss: 0.7629 - acc: 0.7188
Epoch 563/1000
192/192 [==============================] - 0s 62us/sample - loss: 0.7620 - acc: 0.7292
Epoch 564/1000
192/192 [==============================] - 0s 52us/sample - loss: 0.7611 - acc: 0.7292
Epoch 565/1000
192/192 [==============================] - 0s 47us/sample - loss: 0.7594 - acc: 0.7292
Epoch 566/1000
192/192 [==============================] - 0s 47us/sample - loss: 0.7583 - acc: 0.7240
Epoch 567/1000
192/192 [==============================] - 0s 83us/sample - loss: 0.7571 - acc: 0.7188
Epoch 568/1000
192/192 [==============================] - 0s 73us/sample - loss: 0.7563 - acc: 0.7188
Epoch 569/1000
192/192 [==============================] - 0s 47us/sample - loss: 0.7549 - acc: 0.7188
Epoch 570/1000
192/192 [==============================] - 0s 52us/sample - loss: 0.7542 - acc: 0.

192/192 [==============================] - 0s 52us/sample - loss: 0.6859 - acc: 0.7760
Epoch 642/1000
192/192 [==============================] - 0s 78us/sample - loss: 0.6851 - acc: 0.7865
Epoch 643/1000
192/192 [==============================] - 0s 52us/sample - loss: 0.6842 - acc: 0.7760
Epoch 644/1000
192/192 [==============================] - 0s 57us/sample - loss: 0.6835 - acc: 0.7812
Epoch 645/1000
192/192 [==============================] - 0s 47us/sample - loss: 0.6825 - acc: 0.7865
Epoch 646/1000
192/192 [==============================] - 0s 47us/sample - loss: 0.6815 - acc: 0.7865
Epoch 647/1000
192/192 [==============================] - 0s 57us/sample - loss: 0.6810 - acc: 0.7865
Epoch 648/1000
192/192 [==============================] - 0s 73us/sample - loss: 0.6806 - acc: 0.7760
Epoch 649/1000
192/192 [==============================] - 0s 52us/sample - loss: 0.6792 - acc: 0.7760
Epoch 650/1000
192/192 [==============================] - 0s 47us/sample - loss: 0.6782 - acc: 0.

192/192 [==============================] - 0s 42us/sample - loss: 0.6247 - acc: 0.8073
Epoch 721/1000
192/192 [==============================] - 0s 52us/sample - loss: 0.6239 - acc: 0.8073
Epoch 722/1000
192/192 [==============================] - 0s 68us/sample - loss: 0.6230 - acc: 0.8073
Epoch 723/1000
192/192 [==============================] - 0s 52us/sample - loss: 0.6227 - acc: 0.8073
Epoch 724/1000
192/192 [==============================] - 0s 67us/sample - loss: 0.6217 - acc: 0.8073
Epoch 725/1000
192/192 [==============================] - 0s 47us/sample - loss: 0.6209 - acc: 0.8073
Epoch 726/1000
192/192 [==============================] - 0s 58us/sample - loss: 0.6203 - acc: 0.8073
Epoch 727/1000
192/192 [==============================] - 0s 62us/sample - loss: 0.6196 - acc: 0.8073
Epoch 728/1000
192/192 [==============================] - 0s 62us/sample - loss: 0.6188 - acc: 0.8073
Epoch 729/1000
192/192 [==============================] - 0s 47us/sample - loss: 0.6179 - acc: 0.

192/192 [==============================] - 0s 78us/sample - loss: 0.5749 - acc: 0.7969
Epoch 801/1000
192/192 [==============================] - 0s 68us/sample - loss: 0.5747 - acc: 0.8021
Epoch 802/1000
192/192 [==============================] - 0s 62us/sample - loss: 0.5738 - acc: 0.8021
Epoch 803/1000
192/192 [==============================] - 0s 57us/sample - loss: 0.5731 - acc: 0.8021
Epoch 804/1000
192/192 [==============================] - 0s 52us/sample - loss: 0.5726 - acc: 0.8021
Epoch 805/1000
192/192 [==============================] - 0s 47us/sample - loss: 0.5736 - acc: 0.8021
Epoch 806/1000
192/192 [==============================] - 0s 52us/sample - loss: 0.5717 - acc: 0.8021
Epoch 807/1000
192/192 [==============================] - 0s 57us/sample - loss: 0.5712 - acc: 0.8021
Epoch 808/1000
192/192 [==============================] - 0s 57us/sample - loss: 0.5708 - acc: 0.8021
Epoch 809/1000
192/192 [==============================] - 0s 42us/sample - loss: 0.5700 - acc: 0.

192/192 [==============================] - 0s 99us/sample - loss: 0.5387 - acc: 0.7969
Epoch 880/1000
192/192 [==============================] - 0s 68us/sample - loss: 0.5377 - acc: 0.8021
Epoch 881/1000
192/192 [==============================] - 0s 62us/sample - loss: 0.5369 - acc: 0.8021
Epoch 882/1000
192/192 [==============================] - 0s 42us/sample - loss: 0.5368 - acc: 0.8021
Epoch 883/1000
192/192 [==============================] - 0s 52us/sample - loss: 0.5361 - acc: 0.8021
Epoch 884/1000
192/192 [==============================] - 0s 57us/sample - loss: 0.5360 - acc: 0.8021
Epoch 885/1000
192/192 [==============================] - 0s 52us/sample - loss: 0.5357 - acc: 0.8021
Epoch 886/1000
192/192 [==============================] - 0s 67us/sample - loss: 0.5349 - acc: 0.8021
Epoch 887/1000
192/192 [==============================] - 0s 57us/sample - loss: 0.5346 - acc: 0.8073
Epoch 888/1000
192/192 [==============================] - 0s 52us/sample - loss: 0.5342 - acc: 0.

192/192 [==============================] - 0s 78us/sample - loss: 0.4930 - acc: 0.8333
Epoch 960/1000
192/192 [==============================] - 0s 57us/sample - loss: 0.4922 - acc: 0.8333
Epoch 961/1000
192/192 [==============================] - 0s 62us/sample - loss: 0.4914 - acc: 0.8281
Epoch 962/1000
192/192 [==============================] - 0s 47us/sample - loss: 0.4913 - acc: 0.8333
Epoch 963/1000
192/192 [==============================] - 0s 36us/sample - loss: 0.4901 - acc: 0.8333
Epoch 964/1000
192/192 [==============================] - 0s 57us/sample - loss: 0.4896 - acc: 0.8281
Epoch 965/1000
192/192 [==============================] - 0s 57us/sample - loss: 0.4883 - acc: 0.8333
Epoch 966/1000
192/192 [==============================] - 0s 73us/sample - loss: 0.4877 - acc: 0.8333
Epoch 967/1000
192/192 [==============================] - 0s 78us/sample - loss: 0.4870 - acc: 0.8333
Epoch 968/1000
192/192 [==============================] - 0s 57us/sample - loss: 0.4859 - acc: 0.

In [35]:
ypred=ann.predict(x_test)

In [36]:
ypred

array([[4.03422862e-01, 5.82804764e-03, 4.82869595e-02, 2.69857282e-03,
        6.81556528e-03, 2.02580735e-01, 1.58927143e-01, 1.71440110e-01],
       [4.03422862e-01, 5.82804764e-03, 4.82869595e-02, 2.69857282e-03,
        6.81556528e-03, 2.02580735e-01, 1.58927143e-01, 1.71440110e-01],
       [2.30309069e-02, 1.54374967e-13, 1.40383145e-06, 1.27961437e-04,
        9.76816058e-01, 6.46579110e-11, 1.08815816e-17, 2.35880525e-05],
       [3.90332267e-02, 1.43694265e-26, 3.60884168e-03, 5.94017744e-01,
        3.63340229e-01, 5.03507320e-18, 1.77878715e-32, 3.64962168e-19],
       [7.73533387e-03, 7.97989621e-28, 7.09286407e-02, 9.18696225e-01,
        2.63980590e-03, 1.83609165e-17, 2.82137335e-32, 3.68777706e-23],
       [6.59409642e-01, 3.20476865e-05, 9.34214331e-03, 4.09514643e-03,
        1.30152181e-01, 2.40850504e-02, 1.75061723e-05, 1.72866270e-01],
       [8.07371199e-01, 2.05242293e-04, 2.37912647e-02, 4.81662154e-03,
        5.34865893e-02, 2.24064011e-02, 5.28030854e-04, 8.

In [37]:
y_test

array([[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 1.

In [38]:
dataset.head(5)

name  Longitude   Latitude      continent
0    12 -69.982677  12.520880  North America
1     0  66.004734  33.835231           Asia
2     6  17.537368 -12.293361         Africa
3     7 -63.064989  18.223959  North America
4     2  20.049834  41.142450         Europe

In [41]:
yp=ann.predict_classes(sc.transform([[12,-69.982677,12.520880]]))

In [42]:
yp

array([4], dtype=int64)

In [43]:
yp=ann.predict_classes(sc.transform([[0,66.004734,33.835231]]))

In [44]:
yp

array([2], dtype=int64)